### ISSUE TITLE
Hello, I installed on a linux machine and found that the following error was reported. How can I solve it?

### ISSUE THREAD

**Issue by Luzebin1995** [dengwirda/jigsaw-matlab#23]
gmake: Warning: File `Makefile' has modification time 3649 s in the future
gmake[1]: Warning: File `CMakeFiles/Makefile2' has modification time 3649 s in the future
gmake[2]: Warning: File `src/CMakeFiles/marche-cmd.dir/flags.make' has modification time 3649 s in the future
Scanning dependencies of target marche-cmd
gmake[2]: warning:  Clock skew detected.  Your build may be incomplete.
gmake[2]: Warning: File `src/CMakeFiles/marche-cmd.dir/flags.make' has modification time 3648 s in the future
[ 12%] Building CXX object src/CMakeFiles/marche-cmd.dir/jigsaw.cpp.o
In file included from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators.hpp:55:0,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/containers.hpp:49,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/rdelmesh.hpp:61,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/jigsaw.cpp:267:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators/alloc_item.hpp:525:5: error: ‘is_trivially_copyable’ is not a member of ‘std’
     std::is_trivially_copyable <D>::value >
     ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators/alloc_item.hpp:525:5: error: ‘is_trivially_copyable’ is not a member of ‘std’
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators/alloc_item.hpp:525:34:error: template argument 3 is invalid
     std::is_trivially_copyable <D>::value >
                                  ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators/alloc_item.hpp:525:35:error: expected ‘{’ before ‘::’ token
     std::is_trivially_copyable <D>::value >
                                   ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators/alloc_item.hpp:525:43:error: expected initializer before ‘>’ token
     std::is_trivially_copyable <D>::value >
                                           ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/allocators/alloc_item.hpp:575:7: warning: extra ‘;’ [-Wpedantic]
     } ;
       ^
In file included from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/dd_float.hpp:64:0,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/mpfloats.hpp:63,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/geometry.hpp:51,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/rdelmesh.hpp:64,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/jigsaw.cpp:267:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::one_one_mul_full(mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:364:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:369:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::one_one_mul_full(mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:391:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:396:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::one_one_mul_full(mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:418:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:423:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::one_one_sqr_full(mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:440:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:445:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::one_one_sqr_full(mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:464:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:469:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::two_one_mul_full(mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:487:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:500:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::two_one_mul_clip(mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:526:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:537:9: error: ‘else’ without a previous ‘if’
         else        // use fpu
         ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp: In function ‘void mp_float::two_two_mul_clip(mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type, mp_float::real_type&, mp_float::real_type&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:557:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (_has_fma)
            ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_basic.hpp:572:9: error: ‘else’ without a previous ‘if’
         else
         ^
In file included from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/mpfloats.hpp:65:0,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/geometry.hpp:51,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/rdelmesh.hpp:64,
                 from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/jigsaw.cpp:267:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_float.hpp: In function ‘void mp_float::expansion_mul(const mp_float::expansion<NE>&, const mp_float::expansion<NF>&, mp_float::indx_type, mp_float::indx_type, mp_float::expansion<NH>&)’:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_float.hpp:806:16: error: expected ‘(’ before ‘constexpr’
             if constexpr ( NR >= +3 )
                ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_float.hpp:828:13: error: expected ‘}’ before ‘else’
             else
             ^
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_float.hpp: At global scope:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/libcpp/expansion/mp_float.hpp:834:9: error: expected unqualified-id before ‘else’
         else
         ^
In file included from /data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/jigsaw.cpp:838:0:
/data1/public/zblu/software/matlab/matlab2018a/toolbox/creatmpasgrid/jigsaw-matlab-master/external/jigsaw/src/marche.hpp:507:5: error: expected ‘}’ at end of input
     }
     ^
gmake[2]: *** [src/CMakeFiles/marche-cmd.dir/jigsaw.cpp.o] Error 1
gmake[1]: *** [src/CMakeFiles/marche-cmd.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by dengwirda** [comment]
@Luzebin1995, from what I can see, it looks like:
- You may have to update your `c++` compiler --- `jigsaw` requires some `c++17` features (`if constexpr`, etc). I believe `g++ 7` should be enough on linux.
- Your system clock may be offset. This appears to only throw a warning.

Let me know if this works for you or if you have any other issues.

**Comment by dengwirda** [comment]
@Luzebin1995, did this solve the build issues you were having? If so I'll close this...
