### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by yuanweibin** [dengwirda/jigsaw-matlab#26]
Hi,

I am new here and want to use this code in win10.

But I met the problem when I used the 'compile' command in MATLAB.

Here is the error.

>\>\> compile
>\-\- Building for: NMake Makefiles
>CMake Error at CMakeLists.txt:2 (project):
>  Running
>
 >  'nmake' '\-?'
>
>  failed with:
>
>   绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆�
>
>
>CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
>CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
>-- Configuring incomplete, errors occurred!
>See also "E:/localData/mesh3D/jigsaw-matlab-master/external/jigsaw/build/CMakeFiles/CMakeOutput.log".
>绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆�
>CMake Error: Generator: execution of make failed. Make command was: nmake -f Makefile /nologo install && 

I also tried in the shell. But the error is the same.

The "绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆�" in error message means that "System can't find the specified file."

gcc version 8.1.0
cmake version 3.22.0

Thanks.

Yuanwei Bin

**Comment by dengwirda** [comment]
Hi @yuanweibin, do you have a C++ compiler installed on your system? The `...CMAKE_CXX_COMPILER not set...` typically means there's an issue with calling the compiler.

**Comment by yuanweibin** [comment]
> 

Yes. I have installed the MinGW-w64 on my system... I am pretty sure that I have added the 'bin' folder to the PATH.

**Comment by dengwirda** [comment]
Okay, thanks for the info. I don't believe jigsaw has been tested with the MinGW + Win10 combination before, so there may be additional investigation needed on this. I usually run with Win + Visual Studio type workflows, so perhaps this is an alternative?

**Comment by yuanweibin** [comment]
Sure. Let me try it.

**Comment by yuanweibin** [comment]
Thanks. Win + Visual Studio works well.

**Comment by dengwirda** [comment]
Okay, excellent. Thanks for confirming.
