### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Kdiou7** [dengwirda/jigsaw-matlab#27]
Hi, 

I am a new student here and I'm really interested in using your code on Windows 11.
I have uploaded Cmake (cmake version 3.25.2) and Visual studio (2022). I am not sure how can solve this initial problem in MATLAB: 
" 'cmake' is not recognized as an internal or external command, operable program or batch file. "

I am not familiar with CMake, I think I did not understand correctly these steps: 
    "    * cd build
    * cmake .. -DCMAKE_BUILD_TYPE=BUILD_MODE
    * cmake --build . --config BUILD_MODE --target install EXTRAS
    * Delete the temporary BUILD directory."

Any help would be appreciated, Thank you in advance!

**Comment by dengwirda** [comment]
Hi @Kdiou7, if you're looking to run `jigsaw` from within `matlab` there's actually a script available that should hopefully handle building the c++ library behind the scenes:
````
Change matlab working directories to ..\your-install-of-jigsaw-matlab
Run compile.m from the matlab cmd-line
````
This should run `jigsaw`'s cmake-based compile + install from within `matlab`. If there's an issue finding either cmake or msvc it may mean that these programs are not installed correctly on windows.

**Comment by Kdiou7** [comment]
Thank you for your quick response!  I tried to follow your steps, but it does not work with CMake. So, I switch to Miniconda. I have activated the jigsaw environment, now when I go back to compile.m file and run it with Matlab it gives me the same error. 
Maybe I miss something, would it be possible to share with me the exact steps? I am a beginner with these environments.. Or is there a video tutorial I can follow? I appreciate that!

![miniconda-install](https://user-images.githubusercontent.com/123311948/213934312-a3a4f202-ae5c-4fbd-bc85-9b53dcbd1a9b.png)

**Comment by dengwirda** [comment]
@Kdiou7 the expected install process for `jigsaw-matlab` is run the `compile` script from your `jigsaw-matlab` directory:
![jigsaw-matlab-compile-a](https://user-images.githubusercontent.com/10022384/214101150-dd33baaf-0d6c-40d0-bdcb-af11f6e438a3.png)
This should launch a cmake-based build, which should find your msvc compiler if everything is installed correctly. If either cmake or msvc cannot be found it may indicate an issue with how these programs are installed on Windows.

**Comment by dengwirda** [comment]
Hopefully the description above resolved this issue, so I'm closing this. Let me know if not.
