### ISSUE TITLE
build mesh for geometries with internal constraints.

### ISSUE THREAD

**Issue by BinWang0213** [dengwirda/jigsaw-matlab#6]
I used mesh2d to build a very nice mesh with internal constraints (figure below). 
![image](https://user-images.githubusercontent.com/20053787/27965421-5bb8611a-6301-11e7-8bf5-da11c302e533.png)

Now I want to try jigsaw for a better performance. But I don't konw how to define the internal constraints as demo6 in mesh2D. Does this feature support by jigsaw?

In MESH2D, I can define internal constraints as follows:
```
    node = [
         0 ,  0 ;  0 ,  1
         1 ,  1 ;  1 ,  0
         0.3 ,  0.0 ;  0.3 ,  0.05
         0.3 ,  0.1 ;  0.3 ,  0.15
         0.3 ,  0.2 ;  0.3,   0.25
         0.3 ,  0.3 ; 
         0.7 ,  0.5 ; 0.7,   0.55
         0.7 ,  0.6 ; 0.7,   0.65
         0.7,   0.7
        ] ;
    edge = [
         1 ,  2 ;  2 ,  3
         3 ,  4 ;  4 ,  1
         5 ,  6 ;  6 ,  7
         7 ,  8 ;  8,   9
         9 ,  10;  10, 11
         12,  13;  13, 14
         14,  15;  15, 16
        ] ;
   
%-- the geometry must be split into its "exterior" and "int-
%-- erior" components using the optional PART argument. 
    part{1} = [1,2,3,4] ;
```

**Comment by dengwirda** [comment]
Hi Bin,

No, JIGSAW doesn't currently support internal constraints like this. Presently, the best option is to continue to use MESH2D for these type of geometries.

This is on the to-do list for JIGSAW though! I expect to release some fairly comprehensive updates over the next few months, and will make sure this functionality makes it into the next version. I'll leave this issue open until then.

**Comment by BinWang0213** [comment]
Hi, Darren,

Thanks for your nice tool. I am looking forward to the update.

**Comment by dengwirda** [comment]
@BinWang0213 I've introduced new functionality in `JIGSAW-0.9.8` that should support these kind of geometries. Please see `meshdemo(0)` for an example.

In brief: using the (optional) `BOUND` array, it should now be possible to explicitly define which constraints form enclosed areas/volumes in the domain, and which are included as strictly "interior" boundaries. It should also be possible to define geometries that consist of multiple connected "parts". 

Hopefully this will address your needs.

**Comment by BinWang0213** [comment]
It is very nice to see this update.  I'm curious how much kinds of  pairs it support now?
The pairs could be:
1. 0D Point in 2D Surface
2. 1D Line in 2D Surface

3. 0D Point in 3D Volume
4. 1D Line in 3D Volume
5. 2D Surface in 3D Volume

I'm working on geology models which may will have two kinds of pairs at the same time. Such as
![image](https://user-images.githubusercontent.com/20053787/51435350-faa04880-1c3a-11e9-9a4a-4c4ef3ec1694.png)

BTW, I really appreciate for your updates.
Bin

**Comment by dengwirda** [comment]
@BinWang0213 hopefully, there is a fair amount of support for this type of tagging with the latest updates -- the `BOUND` definitions should allow the identification of tetrahedra within different enclosed volumes, and should also allow "interior" surface constraints to be defined. `ID-tag`s are now also propagated through from the geometry for surface and curve constraints. It's generally not possible to classify points in any unique way, as they can be shared by an arbitrary collection of higher-dimensional cells. 

I'll try to make some additional example problems that illustrate the use of `ID-tag`s, etc. Currently `meshdemo(1)` shows how to embed a surface constraint within a tetrahedral mesh, and then find the set of attached triangles via their `ID-tag`s. There shouldn't be a limit on the number of tagged volumes, surfaces, curves, etc that can be defined.

Let me know if you have any thoughts/feedback on this.
